lint scripts

diff --git a/bin/runner b/bin/runner
--- a/bin/runner
+++ b/bin/runner
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 # get the preset from the wrapper scripts
-TYPE=$1
-OPTS=$2
+type=$1
+opts=$2
 
 shift 2
 
@@ -14,8 +14,8 @@ elif [[ "${1,,}" == "prov" ]]; then
   REGIONS=(C A AB AL VI AV BA B BI BU CC CA CS CE CR CO CU SS GI GR GU H HU J GC LE L LU MA ML OR P PO SA TF SG SE SO T TE TO V VA ZA Z)
 fi
 
-ERR=error.log
-rm --force $ERR
+err=error.log
+rm --force "${err}"
 
 # handle kill signs
 trap "echo; exit 1" INT TERM
@@ -23,29 +23,36 @@ trap "echo; exit 1" INT TERM
 for region in "${REGIONS[@]}"
 do
   # feature or report must set the query param "region" in order to get the proper results
-  VAR="REGION="
-  [ $# -gt 0 ] && VAR+=\'$region\'
+  var="REGION="
+  [ $# -gt 0 ] && var+=\'${region}\'
 
-  if [ $TYPE == "feature" ]; then
-    echo -ne "Creando GeoJSON para $region... \t\t\t"
-    FILE=./features/"$region".geojson
-  elif [ $TYPE == "report" ]; then
-    echo -ne "Creando informe para $region... \t\t\t"
-    FILE=./reports/$(date +%Y%m)/"$region".csv
+  if [ "${type}" == "feature" ]; then
+    echo -ne "Creando GeoJSON para ${region}... \t\t\t"
+    file=./features/"${region}".geojson
+  elif [ "${type}" == "report" ]; then
+    echo -ne "Creando informe para ${region}... \t\t\t"
+    file=./reports/$(date +%Y%m)/"${region}".csv
   fi
 
-  mkdir --parents $(dirname "$FILE")
+  mkdir --parents "$(dirname "${file}")"
 
   # run psql with the corresponding variables
-  psql --dbname=osm --single-transaction --variable="ON_ERROR_STOP=1" --variable="$VAR" $OPTS > "$FILE" 2>> $ERR
+  if psql --dbname=osm --single-transaction --variable="ON_ERROR_STOP=1" --variable="${var}" "${opts}" > "${file}" 2>> "${err}"; then
+    echo -ne "[\033[0;32mOK\033[0m]\t\t\t"
+  else
+    echo -ne "[\033[0;31merror\033[0m]\t\t\t"
+  fi
 
-  [ $? -eq 0 ] && echo -ne "[\033[0;32mOK\033[0m]\t\t\t" || echo -ne "[\033[0;31merror\033[0m]\t\t\t"
-  echo -ne $(basename "$FILE")"\t"$(wc -c "$FILE" | cut -d ' ' -f 1 | numfmt --to=si)
-
-  echo
+  echo -ne "$(basename "${file}")$(printf '\t')$(wc -c "${file}" | cut -d ' ' -f 1 | numfmt --to=si)\n"
 done
 
 # display the errors, if any
-[ -s $ERR ] && echo && cat $ERR && exit 1 || rm --force $ERR
+if [ -s "${err}" ]; then
+  echo
+  cat "${err}"
+  exit 1
+else
+  rm --force "${err}"
+fi
 
 exit 0;
