add reports for past months

diff --git a/bin/runner b/bin/runner
--- a/bin/runner
+++ b/bin/runner
@@ -7,38 +7,46 @@ shift 2
 
 REGIONS=("${@:-ES}")
 
-if [[ $1 == "ccaa" ]]; then
+if [[ "${1,,}" == "ccaa" ]]; then
   REGIONS=(AN AS AR CN CB CL CM CT M VC PV EX GA IB RI NA MU)
-elif [[ $1 == "prov" ]]; then
+elif [[ "${1,,}" == "prov" ]]; then
   REGIONS=(C A AB AL VI AV BA B BI BU CC CA CS CE CR CO CU SS GI GR GU H HU J GC LE L LU MA ML OR P PO SA TF SG SE SO T TE TO V VA ZA Z)
 fi
 
 ERR=error.log
-rm -f $ERR
+rm --force $ERR
+
+trap "echo; exit 1" INT TERM
 
 for region in "${REGIONS[@]}"
 do
-  VAR="REGION="
-  [ $# -gt 0 ] && VAR+=\'$region\'
+  if [ $TYPE == "feature" ] || [ $TYPE == "report" ]; then
+    VAR="REGION="
+    [ $# -gt 0 ] && VAR+=\'$region\'
 
-  if [ $TYPE == "feature" ]; then
-    echo -ne "Creando GeoJSON para $region... \t\t\t"
-    FILE=./features/"$region".geojson
-  elif [ $TYPE == "report" ]; then
-    echo -ne "Creando informe para $region... \t\t\t"
-    FILE=./reports/$(date +%Y%m)/"$region".csv
+    if [ $TYPE == "feature" ]; then
+      echo -ne "Creando GeoJSON para $region... \t\t\t"
+      FILE=./features/"$region".geojson
+    elif [ $TYPE == "report" ]; then
+      echo -ne "Creando informe para $region... \t\t\t"
+      FILE=./reports/$(date +%Y%m)/"$region".csv
+    fi
+
+    mkdir --parents $(dirname "$FILE")
+
+    psql --dbname=osm --single-transaction --variable="ON_ERROR_STOP=1" --variable="$VAR" $OPTS > "$FILE" 2>> $ERR
+
+    [ $? -eq 0 ] && echo -ne "[\033[0;32mOK\033[0m]\t\t\t" || echo -ne "[\033[0;31merror\033[0m]\t\t\t"
+    echo -ne "$(basename $FILE)\t$(wc -c $FILE | cut -d ' ' -f 1 | numfmt --to=si)"
+
+    echo
+  elif [ $TYPE == "merge" ]; then
+    awk '(NR == 1) || (FNR > 1)' "./reports/*/$region.csv" > "$region.join.csv"
+    npx mapshaper -i "features/$region.geojson" -clean -join "$region.join.csv" string-fields=id keys=id,id fields=id,name calc='tmp = collect({ [date]: percentage }), values = (tmp || []).reduce((acc, item) => ({ ...acc, ...item }), {}), delete tmp' -o format=topojson "$region.1calle1nombre.topo.json"
+    rm --force "$region.join.csv"
   fi
-
-  mkdir -p $(dirname $FILE)
-
-  psql --dbname=osm --single-transaction --variable="ON_ERROR_STOP=1" --variable="$VAR" $OPTS > $FILE 2>> $ERR
-
-  [ $? -eq 0 ] && echo -ne "[\033[0;32mOK\033[0m]\t\t\t" || echo -ne "[\033[0;31merror\033[0m]\t\t\t"
-  echo -ne "$(basename $FILE)\t$(wc -c $FILE | cut -d ' ' -f 1 | numfmt --to=si)"
-
-  echo
 done
 
-[ -s $ERR ] && echo && cat $ERR && exit 1 || rm -f $ERR
+[ -s $ERR ] && echo && cat $ERR && exit 1 || rm --force $ERR
 
 exit 0;
